<HTML>
<HEAD>
<meta charset="UTF-8">
<title>NoInputDir.initCause - ByteTwist</title>
<link rel="stylesheet" href="../../../style.css">
</HEAD>
<BODY>
<a href="../../index.html">ByteTwist</a>&nbsp;/&nbsp;<a href="../index.html">org.bytetwist.bytetwist.exceptions</a>&nbsp;/&nbsp;<a href="index.html">NoInputDir</a>&nbsp;/&nbsp;<a href="./init-cause.html">initCause</a><br/>
<br/>
<h1>initCause</h1>
<a name="org.bytetwist.bytetwist.exceptions.NoInputDir$initCause(kotlin.Throwable)"></a>
<code><span class="keyword">fun </span><span class="identifier">initCause</span><span class="symbol">(</span><span class="identifier" id="org.bytetwist.bytetwist.exceptions.NoInputDir$initCause(kotlin.Throwable)/cause">cause</span><span class="symbol">:</span>&nbsp;<a href="https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/-throwable/index.html"><span class="identifier">Throwable</span></a><span class="symbol">?</span><span class="symbol">)</span><span class="symbol">: </span><a href="https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/-throwable/index.html"><span class="identifier">Throwable</span></a></code>
<p>Initializes the <em>cause</em> of this throwable to the specified value.
(The cause is the throwable that caused this throwable to get thrown.)</p>
<p>This method can be called at most once.  It is generally called from
within the constructor, or immediately after creating the
throwable.  If this throwable was created
with <a href="#">.Throwable</a> or
<a href="#">.Throwable</a>, this method cannot be called
even once.</p>
<p>An example of using this method on a legacy throwable type
without other support for setting the cause is:</p>
<h3>Parameters</h3>
<p><a name="cause"></a>
<code>cause</code> - the cause (which is saved for later retrieval by the
<a href="#">.getCause</a> method).  (A <code>null</code> value is
permitted, and indicates that the cause is nonexistent or
unknown.)</p>
<h3>Exceptions</h3>
<p><a name="IllegalArgumentException"></a>
<code>IllegalArgumentException</code> - if <code>cause</code> is this
throwable.  (A throwable cannot be its own cause.)</p>
<p><a name="IllegalStateException"></a>
<code>IllegalStateException</code> - if this throwable was
created with <a href="#">.Throwable</a> or
<a href="#">.Throwable</a>, or this method has already
been called on this throwable.</p>
<p><strong>Return</strong><br/>
a reference to this <code>Throwable</code> instance.</p>
<p><strong>Since</strong><br/>
1.4</p>
</BODY>
</HTML>
